// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRRDeRS95JF-sAUomJkXFzFfuD_yEJtg0',
    appId: '1:114710315807:web:4933488b7377c3408a662a',
    messagingSenderId: '114710315807',
    projectId: 'rapport-de-stage-c4eb5',
    authDomain: 'rapport-de-stage-c4eb5.firebaseapp.com',
    storageBucket: 'rapport-de-stage-c4eb5.firebasestorage.app',
    measurementId: 'G-40T26B9KF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOu9mGCaSOYpjW-HgS2cHBH8erDfyuK40',
    appId: '1:114710315807:android:887c24eda16912be8a662a',
    messagingSenderId: '114710315807',
    projectId: 'rapport-de-stage-c4eb5',
    storageBucket: 'rapport-de-stage-c4eb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpMMkfa9CkMzRmTpSsNPwpli8t73bX0Lo',
    appId: '1:114710315807:ios:3b46b75b532c8a038a662a',
    messagingSenderId: '114710315807',
    projectId: 'rapport-de-stage-c4eb5',
    storageBucket: 'rapport-de-stage-c4eb5.firebasestorage.app',
    iosBundleId: 'com.example.monRapportDeStage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpMMkfa9CkMzRmTpSsNPwpli8t73bX0Lo',
    appId: '1:114710315807:ios:3b46b75b532c8a038a662a',
    messagingSenderId: '114710315807',
    projectId: 'rapport-de-stage-c4eb5',
    storageBucket: 'rapport-de-stage-c4eb5.firebasestorage.app',
    iosBundleId: 'com.example.monRapportDeStage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRRDeRS95JF-sAUomJkXFzFfuD_yEJtg0',
    appId: '1:114710315807:web:ec21c3e34c75693e8a662a',
    messagingSenderId: '114710315807',
    projectId: 'rapport-de-stage-c4eb5',
    authDomain: 'rapport-de-stage-c4eb5.firebaseapp.com',
    storageBucket: 'rapport-de-stage-c4eb5.firebasestorage.app',
    measurementId: 'G-CYN11281DP',
  );
}
